'use client';

import React, { useState, useRef } from 'react';
import {
  FileText,
  Presentation,
  Download,
  Loader2,
  Code2,
  Save,
  CheckCircle,
  Eye,
  X,
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

export interface DocGenData {
  type: 'pdf' | 'ppt' | 'document';
  title: string;
  content?: string;
  slides?: Array<{ title: string; bullets: string[] }>;
}

// ── Color themes for PPT slides ──
const SLIDE_THEMES = [
  { bg: '0F172A', accent: '3B82F6', accentLight: '60A5FA', title: 'FFFFFF', text: 'CBD5E1', bullet: '93C5FD' },
  { bg: '1E1B4B', accent: '818CF8', accentLight: 'A5B4FC', title: 'FFFFFF', text: 'C7D2FE', bullet: 'A5B4FC' },
  { bg: '14532D', accent: '22C55E', accentLight: '4ADE80', title: 'FFFFFF', text: 'BBF7D0', bullet: '86EFAC' },
  { bg: '7C2D12', accent: 'F97316', accentLight: 'FB923C', title: 'FFFFFF', text: 'FED7AA', bullet: 'FDBA74' },
  { bg: '1C1917', accent: 'EAB308', accentLight: 'FDE047', title: 'FFFFFF', text: 'FEF9C3', bullet: 'FDE68A' },
];

// ── Detect code language from file extension ──
function detectLanguage(title: string): string {
  const ext = title.split('.').pop()?.toLowerCase() || '';
  const map: Record<string, string> = {
    py: 'python', js: 'javascript', ts: 'typescript', tsx: 'tsx', jsx: 'jsx',
    html: 'html', css: 'css', json: 'json', md: 'markdown', sql: 'sql',
    java: 'java', cpp: 'c++', c: 'c', rs: 'rust', go: 'go', rb: 'ruby',
    php: 'php', sh: 'bash', bash: 'bash', yml: 'yaml', yaml: 'yaml',
    xml: 'xml', swift: 'swift', kt: 'kotlin', dart: 'dart', r: 'r',
  };
  return map[ext] || 'plaintext';
}

function isCodeFile(title: string): boolean {
  const codeExts = ['py', 'js', 'ts', 'tsx', 'jsx', 'html', 'css', 'json', 'sql',
    'java', 'cpp', 'c', 'rs', 'go', 'rb', 'php', 'sh', 'bash', 'yml', 'yaml',
    'xml', 'swift', 'kt', 'dart', 'r', 'h', 'hpp', 'cs', 'lua', 'pl', 'scala'];
  const ext = title.split('.').pop()?.toLowerCase() || '';
  return codeExts.includes(ext);
}

async function saveToServer(fileName: string, fileData: string, fileType: string) {
  try {
    const response = await fetch('/api/save-file', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ fileName, fileData, fileType }),
    });
    return await response.json();
  } catch (error) {
    console.error('Failed to save file to server:', error);
    return null;
  }
}

// ── Styled PDF hidden render ──
function StyledPdfRender({ data, hiddenRef }: { data: DocGenData; hiddenRef: React.RefObject<HTMLDivElement | null> }) {
  return (
    <div className="overflow-hidden h-0 w-0 absolute opacity-0 pointer-events-none">
      <div
        ref={hiddenRef}
        style={{
          width: '800px',
          fontFamily: "'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
          backgroundColor: '#ffffff',
          color: '#1a1a2e',
          padding: '0',
          lineHeight: '1.7',
        }}
      >
        {/* Cover header bar */}
        <div style={{
          background: 'linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%)',
          padding: '48px 56px 40px',
          color: '#ffffff',
        }}>
          <div style={{
            width: '60px',
            height: '4px',
            backgroundColor: '#3b82f6',
            borderRadius: '2px',
            marginBottom: '20px',
          }} />
          <h1 style={{
            fontSize: '32px',
            fontWeight: '700',
            margin: '0 0 8px 0',
            letterSpacing: '-0.5px',
            lineHeight: '1.2',
          }}>
            {data.title}
          </h1>
          <p style={{
            fontSize: '13px',
            color: '#94a3b8',
            margin: '0',
            fontWeight: '500',
          }}>
            Generated by Purn AI &nbsp;•&nbsp; {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
        </div>

        {/* Content body */}
        <div style={{ padding: '40px 56px 56px' }}>
          <PdfMarkdownRenderer content={data.content || ''} />
        </div>

        {/* Footer */}
        <div style={{
          borderTop: '1px solid #e2e8f0',
          padding: '16px 56px',
          display: 'flex',
          justifyContent: 'space-between',
          fontSize: '10px',
          color: '#94a3b8',
        }}>
          <span>{data.title}</span>
          <span>Purn AI</span>
        </div>
      </div>
    </div>
  );
}

// ── Custom markdown renderer for PDF with inline styles ──
function PdfMarkdownRenderer({ content }: { content: string }) {
  return (
    <div>
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          h1: ({ children }) => (
            <h1 style={{
              fontSize: '26px', fontWeight: '700', color: '#0f172a',
              margin: '32px 0 12px', borderBottom: '2px solid #3b82f6',
              paddingBottom: '8px', letterSpacing: '-0.3px',
            }}>{children}</h1>
          ),
          h2: ({ children }) => (
            <h2 style={{
              fontSize: '21px', fontWeight: '600', color: '#1e3a5f',
              margin: '28px 0 10px', borderLeft: '4px solid #3b82f6',
              paddingLeft: '12px',
            }}>{children}</h2>
          ),
          h3: ({ children }) => (
            <h3 style={{
              fontSize: '17px', fontWeight: '600', color: '#334155',
              margin: '20px 0 8px',
            }}>{children}</h3>
          ),
          p: ({ children }) => (
            <p style={{
              fontSize: '14px', color: '#374151', lineHeight: '1.8',
              margin: '0 0 14px',
            }}>{children}</p>
          ),
          ul: ({ children }) => (
            <ul style={{
              margin: '8px 0 16px 0', paddingLeft: '0', listStyle: 'none',
            }}>{children}</ul>
          ),
          ol: ({ children }) => (
            <ol style={{
              margin: '8px 0 16px 20px', paddingLeft: '0',
              fontSize: '14px', color: '#374151', lineHeight: '1.8',
            }}>{children}</ol>
          ),
          li: ({ children }) => (
            <li style={{
              fontSize: '14px', color: '#374151', lineHeight: '1.8',
              marginBottom: '6px', paddingLeft: '20px', position: 'relative',
            }}>
              <span style={{
                position: 'absolute', left: '0', top: '8px',
                width: '6px', height: '6px', borderRadius: '50%',
                backgroundColor: '#3b82f6', display: 'inline-block',
              }} />
              {children}
            </li>
          ),
          strong: ({ children }) => (
            <strong style={{ fontWeight: '700', color: '#0f172a' }}>{children}</strong>
          ),
          em: ({ children }) => (
            <em style={{ fontStyle: 'italic', color: '#4b5563' }}>{children}</em>
          ),
          blockquote: ({ children }) => (
            <blockquote style={{
              borderLeft: '4px solid #3b82f6', backgroundColor: '#f0f7ff',
              padding: '12px 16px', margin: '16px 0', borderRadius: '0 8px 8px 0',
              fontSize: '14px', color: '#1e40af',
            }}>{children}</blockquote>
          ),
          code: ({ children, className }) => {
            const isBlock = className?.includes('language-');
            if (isBlock) {
              return (
                <pre style={{
                  backgroundColor: '#0f172a', color: '#e2e8f0', padding: '16px 20px',
                  borderRadius: '8px', fontSize: '12.5px', lineHeight: '1.6',
                  overflow: 'auto', margin: '16px 0', border: '1px solid #1e293b',
                  fontFamily: "'Fira Code', 'Consolas', monospace",
                }}>
                  <code>{children}</code>
                </pre>
              );
            }
            return (
              <code style={{
                backgroundColor: '#eff6ff', color: '#1e40af', padding: '2px 6px',
                borderRadius: '4px', fontSize: '13px',
                fontFamily: "'Fira Code', 'Consolas', monospace",
              }}>{children}</code>
            );
          },
          table: ({ children }) => (
            <table style={{
              width: '100%', borderCollapse: 'collapse', margin: '16px 0',
              fontSize: '13px',
            }}>{children}</table>
          ),
          thead: ({ children }) => (
            <thead style={{
              backgroundColor: '#0f172a', color: '#ffffff',
            }}>{children}</thead>
          ),
          th: ({ children }) => (
            <th style={{
              padding: '10px 14px', textAlign: 'left', fontWeight: '600',
              fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.5px',
            }}>{children}</th>
          ),
          td: ({ children }) => (
            <td style={{
              padding: '10px 14px', borderBottom: '1px solid #e2e8f0',
              color: '#374151',
            }}>{children}</td>
          ),
          tr: ({ children }) => (
            <tr>{children}</tr>
          ),
          hr: () => (
            <hr style={{
              border: 'none', height: '1px', backgroundColor: '#e2e8f0',
              margin: '24px 0',
            }} />
          ),
          a: ({ children, href }) => (
            <a href={href} style={{
              color: '#2563eb', textDecoration: 'underline',
            }}>{children}</a>
          ),
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
}

// ── Preview modal ──
function PreviewModal({ data, onClose }: { data: DocGenData; onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm" onClick={onClose}>
      <div
        className="bg-[#1a1a1c] border border-gray-700 rounded-2xl w-[90vw] max-w-3xl max-h-[85vh] overflow-hidden flex flex-col shadow-2xl"
        onClick={e => e.stopPropagation()}
      >
        {/* Modal header */}
        <div className="flex items-center justify-between px-5 py-3 border-b border-gray-800">
          <div className="flex items-center gap-2">
            {data.type === 'ppt' ? <Presentation size={16} className="text-orange-400" /> :
              data.type === 'pdf' ? <FileText size={16} className="text-red-400" /> :
                <Code2 size={16} className="text-green-400" />}
            <span className="text-sm font-semibold text-gray-200">{data.title}</span>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-gray-800 transition-colors">
            <X size={16} className="text-gray-400" />
          </button>
        </div>

        {/* Modal body */}
        <div className="flex-1 overflow-y-auto">
          {data.type === 'ppt' && data.slides ? (
            <div className="p-4 space-y-3">
              {/* Title slide preview */}
              <div className="rounded-xl overflow-hidden border border-gray-700 aspect-video flex flex-col items-center justify-center"
                style={{ background: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)' }}>
                <div className="w-16 h-1 bg-blue-500 rounded mb-4" />
                <h2 className="text-xl font-bold text-white text-center px-6">{data.title}</h2>
                <p className="text-xs text-gray-400 mt-2">Generated by Purn AI</p>
              </div>
              {/* Content slides */}
              {data.slides.map((slide, i) => {
                const theme = SLIDE_THEMES[i % SLIDE_THEMES.length];
                return (
                  <div key={i} className="rounded-xl overflow-hidden border border-gray-700 aspect-video p-6 flex flex-col"
                    style={{ backgroundColor: `#${theme.bg}` }}>
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-[10px] font-mono px-1.5 py-0.5 rounded"
                        style={{ backgroundColor: `#${theme.accent}30`, color: `#${theme.accentLight}` }}>
                        {String(i + 1).padStart(2, '0')}
                      </span>
                    </div>
                    <h3 className="text-base font-bold mb-1" style={{ color: `#${theme.title}` }}>
                      {slide.title}
                    </h3>
                    <div className="w-10 h-0.5 rounded mb-3" style={{ backgroundColor: `#${theme.accent}` }} />
                    <ul className="space-y-1.5 flex-1">
                      {slide.bullets.map((b, j) => (
                        <li key={j} className="flex items-start gap-2 text-xs" style={{ color: `#${theme.text}` }}>
                          <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ backgroundColor: `#${theme.bullet}` }} />
                          {b}
                        </li>
                      ))}
                    </ul>
                  </div>
                );
              })}
            </div>
          ) : data.type === 'document' && isCodeFile(data.title) ? (
            <div className="relative">
              <div className="flex items-center gap-2 px-4 py-2 bg-[#0d1117] border-b border-gray-800">
                <Code2 size={14} className="text-gray-500" />
                <span className="text-xs text-gray-400 font-mono">{data.title}</span>
                <span className="text-[10px] text-gray-600 ml-auto">{detectLanguage(data.title)}</span>
              </div>
              <pre className="p-4 bg-[#0d1117] text-sm text-gray-300 font-mono leading-relaxed overflow-auto max-h-[60vh]">
                <code>{data.content}</code>
              </pre>
            </div>
          ) : (
            <div className="p-6 prose prose-invert prose-sm max-w-full overflow-auto max-h-[60vh]">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {data.content || ''}
              </ReactMarkdown>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ── Main DocumentCard ──
export default function DocumentCard({ data }: { data: DocGenData }) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [savedPath, setSavedPath] = useState<string | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  const hiddenContentRef = useRef<HTMLDivElement>(null);

  const handleDownloadPdf = async () => {
    try {
      setIsGenerating(true);
      const jsPDFModule = await import('jspdf');
      const jsPDF = jsPDFModule.default;
      const html2canvas = (await import('html2canvas')).default;

      if (!hiddenContentRef.current) return;

      const canvas = await html2canvas(hiddenContentRef.current, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#ffffff',
        logging: false,
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'px', format: 'a4' });

      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const ratio = pdfWidth / canvas.width;
      const scaledHeight = canvas.height * ratio;

      let heightLeft = scaledHeight;
      let position = 0;
      let page = 0;

      while (heightLeft > 0) {
        if (page > 0) pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, scaledHeight);
        heightLeft -= pdfHeight;
        position -= pdfHeight;
        page++;
      }

      const fileName = `${data.title || 'Document'}.pdf`;
      pdf.save(fileName);

      const base64 = pdf.output('datauristring').split(',')[1];
      await saveToServer(fileName, base64, 'pdf');
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadPpt = async () => {
    try {
      setIsGenerating(true);
      const pptxgen = (await import('pptxgenjs')).default;
      const pres = new pptxgen();
      pres.layout = 'LAYOUT_16x9';
      pres.author = 'Purn AI';

      // ── Title Slide ──
      const titleSlide = pres.addSlide();
      titleSlide.background = { fill: '0F172A' };

      // Accent bar top
      titleSlide.addShape('rect' as any, {
        x: 0, y: 0, w: '100%', h: 0.06,
        fill: { color: '3B82F6' },
      });

      // Decorative circle
      titleSlide.addShape('ellipse' as any, {
        x: 7.5, y: 0.5, w: 2.5, h: 2.5,
        fill: { color: '1E3A5F', transparency: 50 },
      });

      // Small accent line
      titleSlide.addShape('rect' as any, {
        x: 1.2, y: 2.2, w: 0.8, h: 0.05,
        fill: { color: '3B82F6' },
      });

      titleSlide.addText(data.title || 'Presentation', {
        x: 1.2, y: 2.5, w: 7.5,
        fontSize: 36, bold: true, color: 'FFFFFF',
        fontFace: 'Arial', lineSpacing: 42,
      });

      titleSlide.addText('Generated by Purn AI', {
        x: 1.2, y: 4.2, w: 5,
        fontSize: 14, color: '64748B', fontFace: 'Arial',
      });

      titleSlide.addText(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), {
        x: 1.2, y: 4.6, w: 5,
        fontSize: 11, color: '475569', fontFace: 'Arial',
      });

      // ── Content Slides ──
      if (data.slides && Array.isArray(data.slides)) {
        data.slides.forEach((slide, idx) => {
          const theme = SLIDE_THEMES[idx % SLIDE_THEMES.length];
          const s = pres.addSlide();

          s.background = { fill: theme.bg };

          // Top accent bar
          s.addShape('rect' as any, {
            x: 0, y: 0, w: '100%', h: 0.04,
            fill: { color: theme.accent },
          });

          // Side stripe
          s.addShape('rect' as any, {
            x: 0, y: 0, w: 0.06, h: '100%',
            fill: { color: theme.accent },
          });

          // Slide number badge
          s.addText(String(idx + 1).padStart(2, '0'), {
            x: 8.8, y: 0.3, w: 0.8, h: 0.4,
            fontSize: 11, color: theme.accentLight, fontFace: 'Arial',
            align: 'right',
          });

          // Title
          s.addText(slide.title, {
            x: 0.7, y: 0.4, w: 8,
            fontSize: 26, bold: true, color: theme.title,
            fontFace: 'Arial',
          });

          // Divider line under title
          s.addShape('rect' as any, {
            x: 0.7, y: 1.15, w: 1.2, h: 0.04,
            fill: { color: theme.accent },
          });

          // Bullet points
          if (slide.bullets && Array.isArray(slide.bullets)) {
            const bulletItems = slide.bullets.map((b, bIdx) => ({
              text: b,
              options: {
                fontSize: 17,
                color: theme.text,
                bullet: {
                  type: 'number' as const,
                  numberType: undefined,
                  code: '25CF',     // filled circle ●
                  style: undefined,
                  startAt: undefined,
                  indent: undefined,
                },
                paraSpaceAfter: 8,
                indentLevel: 0,
              } as any,
            }));

            s.addText(bulletItems, {
              x: 0.7, y: 1.45, w: 8.5, h: 3.6,
              fontSize: 17, color: theme.text,
              valign: 'top', fontFace: 'Arial',
              lineSpacing: 30,
            });
          }

          // Bottom decorative element
          s.addShape('rect' as any, {
            x: 0.7, y: 5.0, w: 0.5, h: 0.03,
            fill: { color: theme.accent, transparency: 50 },
          });
        });

        // ── Thank You / End Slide ──
        const endSlide = pres.addSlide();
        endSlide.background = { fill: '0F172A' };

        endSlide.addShape('rect' as any, {
          x: 0, y: 5.25, w: '100%', h: 0.06,
          fill: { color: '3B82F6' },
        });

        endSlide.addText('Thank You', {
          x: 0, y: '35%', w: '100%',
          fontSize: 40, bold: true, color: 'FFFFFF',
          fontFace: 'Arial', align: 'center',
        });

        endSlide.addText('This presentation was generated by Purn AI', {
          x: 0, y: '55%', w: '100%',
          fontSize: 14, color: '64748B', fontFace: 'Arial', align: 'center',
        });
      }

      const fileName = `${data.title || 'Presentation'}.pptx`;
      const pptxData = await pres.write({ outputType: 'base64' });
      await saveToServer(fileName, pptxData as string, 'pptx');
      await pres.writeFile({ fileName });
    } catch (error) {
      console.error('Error generating PPT:', error);
      alert('Failed to generate PPT. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadDocument = async () => {
    try {
      setIsGenerating(true);
      const content = data.content || '';
      const fileName = data.title || 'document.txt';

      const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = fileName;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      const base64 = btoa(unescape(encodeURIComponent(content)));
      await saveToServer(fileName, base64, 'document');
    } catch (error) {
      console.error('Error generating document:', error);
      alert('Failed to generate document. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = () => {
    if (data.type === 'pdf') handleDownloadPdf();
    else if (data.type === 'ppt') handleDownloadPpt();
    else handleDownloadDocument();
  };

  const handleSaveToProject = async () => {
    try {
      setIsSaving(true);

      if (data.type === 'ppt') {
        // For PPT: generate and save the actual pptx binary
        const pptxgen = (await import('pptxgenjs')).default;
        const pres = new pptxgen();
        pres.layout = 'LAYOUT_16x9';
        // Re-build in same way as download (abbreviated for save)
        const titleSlide = pres.addSlide();
        titleSlide.background = { fill: '0F172A' };
        titleSlide.addText(data.title || 'Presentation', {
          x: 1.2, y: 2.5, w: 7.5, fontSize: 36, bold: true, color: 'FFFFFF', fontFace: 'Arial',
        });
        if (data.slides) {
          data.slides.forEach((slide, idx) => {
            const theme = SLIDE_THEMES[idx % SLIDE_THEMES.length];
            const s = pres.addSlide();
            s.background = { fill: theme.bg };
            s.addText(slide.title, { x: 0.7, y: 0.4, w: 8, fontSize: 26, bold: true, color: theme.title, fontFace: 'Arial' });
            if (slide.bullets) {
              s.addText(slide.bullets.map(b => ({ text: b, options: { bullet: true, color: theme.text, fontSize: 17 } })), {
                x: 0.7, y: 1.4, w: 8.5, h: 3.6, fontSize: 17, color: theme.text, valign: 'top', fontFace: 'Arial', lineSpacing: 30,
              });
            }
          });
        }
        const pptxData = await pres.write({ outputType: 'base64' });
        const fileName = `${data.title || 'Presentation'}.pptx`;
        const result = await saveToServer(fileName, pptxData as string, 'pptx');
        if (result?.success) { setSaved(true); setSavedPath(result.filePath); }
        else alert('Failed to save PPT.');
      } else if (data.type === 'pdf') {
        // For PDF: generate and save the actual pdf binary
        const jsPDFModule = await import('jspdf');
        const jsPDF = jsPDFModule.default;
        const html2canvas = (await import('html2canvas')).default;
        if (hiddenContentRef.current) {
          const canvas = await html2canvas(hiddenContentRef.current, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
          const pdf = new jsPDF({ orientation: 'portrait', unit: 'px', format: 'a4' });
          const pdfWidth = pdf.internal.pageSize.getWidth();
          const pdfHeight = pdf.internal.pageSize.getHeight();
          const ratio = pdfWidth / canvas.width;
          const scaledHeight = canvas.height * ratio;
          let heightLeft = scaledHeight;
          let position = 0;
          let page = 0;
          while (heightLeft > 0) {
            if (page > 0) pdf.addPage();
            pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, position, pdfWidth, scaledHeight);
            heightLeft -= pdfHeight;
            position -= pdfHeight;
            page++;
          }
          const base64 = pdf.output('datauristring').split(',')[1];
          const fileName = `${data.title || 'Document'}.pdf`;
          const result = await saveToServer(fileName, base64, 'pdf');
          if (result?.success) { setSaved(true); setSavedPath(result.filePath); }
          else alert('Failed to save PDF.');
        }
      } else {
        const content = data.content || '';
        const fileName = data.title || 'document.txt';
        const base64 = btoa(unescape(encodeURIComponent(content)));
        const result = await saveToServer(fileName, base64, data.type);
        if (result?.success) { setSaved(true); setSavedPath(result.filePath); }
        else alert('Failed to save file.');
      }
    } catch (error) {
      console.error('Error saving:', error);
    } finally {
      setIsSaving(false);
    }
  };

  const getIcon = () => {
    if (data.type === 'pdf') return <FileText size={22} />;
    if (data.type === 'ppt') return <Presentation size={22} />;
    if (isCodeFile(data.title)) return <Code2 size={22} />;
    return <FileText size={22} />;
  };

  const getTypeLabel = () => {
    if (data.type === 'pdf') return 'PDF Document';
    if (data.type === 'ppt') return `PowerPoint · ${data.slides?.length || 0} slides`;
    if (isCodeFile(data.title)) return detectLanguage(data.title).toUpperCase() + ' File';
    return 'Document';
  };

  const getTypeColor = () => {
    if (data.type === 'pdf') return 'bg-red-500/10 text-red-400 border-red-500/20';
    if (data.type === 'ppt') return 'bg-orange-500/10 text-orange-400 border-orange-500/20';
    if (isCodeFile(data.title)) return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20';
    return 'bg-blue-500/10 text-blue-400 border-blue-500/20';
  };

  const getAccent = () => {
    if (data.type === 'pdf') return 'border-red-500/30';
    if (data.type === 'ppt') return 'border-orange-500/30';
    return 'border-emerald-500/30';
  };

  return (
    <>
      <div className={`mt-3 w-full max-w-md rounded-xl border bg-[#1A1A1C] overflow-hidden ${getAccent()}`}>
        {/* Mini preview strip */}
        {data.type === 'ppt' && data.slides && data.slides.length > 0 && (
          <div className="flex gap-1 p-2 pb-0 overflow-x-auto">
            {data.slides.slice(0, 4).map((slide, i) => {
              const theme = SLIDE_THEMES[i % SLIDE_THEMES.length];
              return (
                <div key={i} className="flex-shrink-0 w-24 h-14 rounded-md overflow-hidden border border-gray-700 p-1.5 flex flex-col"
                  style={{ backgroundColor: `#${theme.bg}` }}>
                  <p className="text-[6px] font-bold truncate" style={{ color: `#${theme.title}` }}>{slide.title}</p>
                  <div className="w-4 h-[1px] mt-0.5 mb-0.5 rounded" style={{ backgroundColor: `#${theme.accent}` }} />
                  {slide.bullets.slice(0, 2).map((b, j) => (
                    <p key={j} className="text-[5px] truncate" style={{ color: `#${theme.text}` }}>• {b}</p>
                  ))}
                </div>
              );
            })}
            {data.slides.length > 4 && (
              <div className="flex-shrink-0 w-14 h-14 rounded-md border border-gray-700 flex items-center justify-center bg-gray-800/50">
                <span className="text-[10px] text-gray-400">+{data.slides.length - 4}</span>
              </div>
            )}
          </div>
        )}

        {data.type === 'document' && data.content && (
          <div className="mx-3 mt-3 max-h-[100px] overflow-hidden rounded-lg bg-[#0d1117] border border-gray-800 relative">
            {isCodeFile(data.title) ? (
              <div>
                <div className="flex items-center gap-1.5 px-3 py-1 border-b border-gray-800">
                  <span className="w-2 h-2 rounded-full bg-red-500/60" />
                  <span className="w-2 h-2 rounded-full bg-yellow-500/60" />
                  <span className="w-2 h-2 rounded-full bg-green-500/60" />
                  <span className="text-[9px] text-gray-500 ml-1.5 font-mono">{data.title}</span>
                </div>
                <pre className="p-2.5 text-[11px] text-gray-400 font-mono leading-relaxed overflow-hidden">
                  <code>{data.content.slice(0, 400)}</code>
                </pre>
              </div>
            ) : (
              <div className="p-2.5 text-[11px] text-gray-400 leading-relaxed overflow-hidden">
                {data.content.slice(0, 300)}
              </div>
            )}
            <div className="absolute bottom-0 left-0 right-0 h-8 bg-gradient-to-t from-[#0d1117] to-transparent" />
          </div>
        )}

        {/* Card info */}
        <div className="p-3 flex items-center gap-3">
          <div className={`p-2 rounded-lg flex-shrink-0 border ${getTypeColor()}`}>
            {getIcon()}
          </div>
          <div className="flex-1 min-w-0">
            <h3 className="text-sm font-semibold text-gray-100 truncate">
              {data.title || 'Generated Document'}
            </h3>
            <p className="text-[11px] text-gray-400 mt-0.5 font-medium">
              {getTypeLabel()}
            </p>
          </div>
        </div>

        {/* Action buttons */}
        <div className="px-3 pb-3 flex gap-1.5">
          <button
            onClick={() => setShowPreview(true)}
            className="flex items-center justify-center gap-1.5 py-2 px-3 bg-gray-800/80 hover:bg-gray-700 text-gray-300 rounded-lg text-xs font-medium transition-colors border border-gray-700/50"
          >
            <Eye size={13} />
            Preview
          </button>
          <button
            onClick={handleDownload}
            disabled={isGenerating}
            className="flex-1 flex items-center justify-center gap-1.5 py-2 px-3 bg-gray-800/80 hover:bg-gray-700 text-gray-200 rounded-lg text-xs font-medium transition-colors disabled:opacity-50 border border-gray-700/50"
          >
            {isGenerating ? (
              <><Loader2 size={13} className="animate-spin" /> Generating...</>
            ) : (
              <><Download size={13} /> Download</>
            )}
          </button>
          <button
            onClick={handleSaveToProject}
            disabled={isSaving || saved}
            className={`flex items-center justify-center gap-1.5 py-2 px-3 rounded-lg text-xs font-medium transition-colors border ${
              saved
                ? 'bg-green-500/10 text-green-400 border-green-500/20'
                : 'bg-gray-800/80 hover:bg-gray-700 text-gray-200 border-gray-700/50 disabled:opacity-50'
            }`}
          >
            {saved ? <><CheckCircle size={13} /> Saved</> :
              isSaving ? <Loader2 size={13} className="animate-spin" /> :
                <><Save size={13} /> Save</>}
          </button>
        </div>

        {saved && savedPath && (
          <div className="px-3 pb-2.5">
            <p className="text-[10px] text-green-400/60">Saved to generations/ folder</p>
          </div>
        )}

        {/* Hidden PDF render */}
        {data.type === 'pdf' && (
          <StyledPdfRender data={data} hiddenRef={hiddenContentRef} />
        )}
      </div>

      {/* Preview modal */}
      {showPreview && <PreviewModal data={data} onClose={() => setShowPreview(false)} />}
    </>
  );
}
